# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/wulian/KWS-SOC/KWS-SOC.srcs/sources_1/ip/kws_0/kws_0.xci
# IP: The module: 'kws_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/wulian/KWS-SOC/KWS-SOC.srcs/sources_1/ip/kws_0/constraints/kws_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kws_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/wulian/KWS-SOC/KWS-SOC.srcs/sources_1/ip/kws_0/kws_0.xci
# IP: The module: 'kws_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/wulian/KWS-SOC/KWS-SOC.srcs/sources_1/ip/kws_0/constraints/kws_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kws_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
