webtalk_init -webtalk_dir F:/VivadoProject/wujiankws_opensource/wujiankws_opensource/wujiankws.sim/sim_1/behav/xsim/xsim.dir/wujian100_open_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 23 11:14:20 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d41508e8-4604-490c-83cb-6a0d79fb9980" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ecc7509f9ed44b069e17edd181dafb3c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "101" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700X 8-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4050 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "628075 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "13.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "70112_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1469985126 -regid "" -xml F:/VivadoProject/wujiankws_opensource/wujiankws_opensource/wujiankws.sim/sim_1/behav/xsim/xsim.dir/wujian100_open_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/VivadoProject/wujiankws_opensource/wujiankws_opensource/wujiankws.sim/sim_1/behav/xsim/xsim.dir/wujian100_open_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/VivadoProject/wujiankws_opensource/wujiankws_opensource/wujiankws.sim/sim_1/behav/xsim/xsim.dir/wujian100_open_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
